### ISSUE TITLE
Question about Grippermodel variables

### ISSUE THREAD

**Issue by PalMadDog** [maximeadjigble/grasplocomo#5]
Could you explain what frictionAngle and NrotSampled represents in dxGripperModel.h?
![image](https://user-images.githubusercontent.com/97889536/166253858-eaa2751b-0849-4cf0-b809-7f466e2604ea.png)

**Comment by maximeadjigble** [comment]
frictionAngle is the angle of the friction cone used for force closure analysis. Smaller values will lead to less grasps but more stable ones and larger values will give more variety

NrotSampled  is the number of grasps generated for each feature. (A feature is composed of two points with surface normals).
Because, it is a parallel gripper that is used, for every feature, it is possible to rotate the gripper around the line formed by the two contact points to generate grasps, so that's what NrotSampled  is used for.
